all:
	pdflatex ieeeconf

full:
	pdflatex ieeeconf
	bibtex ieeeconf
	pdflatex ieeeconf
	pdflatex ieeeconf

clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *.blg)
